version: "3.3"

services:
  app:
    build: .
    ports:
      - "80:80"
    env_file:
      - .env
    restart: always    

  postgres:
    image: postgres:latest   
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastapi-basics

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:        
  postgres-db: